name: Apply DNS changes
on:
  push:
    paths:
      - dns/**
      - .github/worksflows/dns.yaml
    branches:
      - main

env:
  TF_TOKEN_app_terraform_io: ${{ secrets.TF_TOKEN_APP_TERRAFORM_IO }}
  CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}

jobs:
  terraform-plan:
    runs-on: ubuntu-22.04
    environment: dns-tf-plan
    container:
      image: hashicorp/terraform:1.12.2
    defaults:
      run:
        working-directory: dns
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Terraform init
        run: terraform init -input=false
      - name: Terraform plan
        run: terraform plan -out=dns.plan -input=false -var "cloudflare_api_token=$CLOUDFLARE_API_TOKEN"
      - name: Archive terraform plan
        uses: actions/upload-artifact@v4
        with:
          name: dns.plan
          path: dns/dns.plan
  
  terraform-apply:
    needs: terraform-plan
    runs-on: ubuntu-22.04
    container:
      image: hashicorp/terraform:1.12.2
    environment: dns-tf-apply
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Download a single artifact
        uses: actions/download-artifact@v4
        with:
          name: dns.plan
      - name: Terraform apply
        run: terraform apply dns.plan
