name: Syntax check
on: [push]
jobs:
  syntax-check:
    runs-on: ubuntu-22.04
    environment: dns
    container:
      image: hashicorp/terraform:1.12.2
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Echo secret
        run: echo $TF_TOKEN_APP_TERRAFORM_IO
        env:
          TF_TOKEN_app_terraform_io: ${{ secrets.TERRAFORM_API_TOKEN }}
      # - name: Terraform init
      #   run: cd dns && terraform init
