name: Apply DNS
on:
  push:
    branches:
      - main
env:
  TF_TOKEN_app_terraform_io: ${{ secrets.TF_TOKEN_APP_TERRAFORM_IO }}
  CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}

jobs:
  terraform-plan-and-apply:
    runs-on: ubuntu-22.04
    environment: dns
    defaults:
      run:
        working-directory: dns
    container:
      image: hashicorp/terraform:1.12.2
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Terraform init
        run: terraform init -input=false
      - name: Terraform plan
        run: terraform plan -out=dns.plan -input=false -var "cloudflare_api_token=$CLOUDFLARE_API_TOKEN"
      - name: Aprove terraform plan before pushing changes
        uses: trstringer/manual-approval@v1
        with:
          secret: ${{ github.TOKEN }}
          approvers: matuzalemmuller
          minimum-approvals: 1
          issue-title: "Deploying DNS changes to CloudFlare"
          issue-body: "Please approve or deny the DNS changes."
          issue-body-file-path: dns.plan
          exclude-workflow-initiator-as-approver: false
          fail-on-denial: true
          additional-approved-words: ''
          additional-denied-words: ''
      - name: Terraform apply
        run: terraform apply dns.plan
