name: Apply DNS
on: [push]

env:
  TF_TOKEN_app_terraform_io: ${{ secrets.TF_TOKEN_APP_TERRAFORM_IO }}

jobs:
  syntax-check:
    runs-on: ubuntu-22.04
    environment: dns
    defaults:
      run:
        working-directory: dns
    container:
      image: hashicorp/terraform:1.12.2
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Terraform init
        run: terraform init
      - name: Terraform plan
        run: terraform plan -var "cloudflare_api_token=$CLOUDFLARE_API_TOKEN"
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
