name: Raspberry Pi

on:
  push:
    paths:
      - raspberry-pi/ansible/**
      - .github/workflows/raspberry-pi.yaml

jobs:
  syntax-check:
    runs-on: ubuntu-22.04
    container:
      image: matuzalemmuller/setup-workstation:latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Run ansible-playbook --syntax-check
        run: ansible-playbook raspberry-pi/ansible/playbook/setup-server.yaml --syntax-check
